added drag and drop to selected files container
CCExtractor/ccextractorfluttergui pull request #10
Opened 2021-11-22 18:59 UTC by AshishSingh2001

added drag and drop as mentioned in issue #6  using [desktop_drop](https://pub.dev/packages/desktop_drop) for selected container in Dashboard

2021-11-22 19:45 UTC, Techno-Disaster commented
strange I would have expected some windows and macOS registrants generated too. Have you tested this on windows or macOS? Maybe you don't  have windows and macOS enabled in your flutter config desktop so they weren't generated?

2021-11-22 19:46 UTC, Techno-Disaster commented
Tests failed can you look into it?

2021-11-23 02:08 UTC, AshishSingh2001 commented
i could try checking it in windows and will see why the tests failed

2021-11-23 10:57 UTC, Techno-Disaster requested changes

2021-11-23 10:57 UTC, Techno-Disaster commented on lib/bloc_observer.dart
> +  void onTransition(Bloc bloc, Transition transition) {
IIRC this creates a lot of verbose logs during extraction.

2021-11-23 18:23 UTC, AshishSingh2001 commented on lib/bloc_observer.dart
> +  void onTransition(Bloc bloc, Transition transition) {
reverted the bloc observer changes in other commit

2021-11-26 15:55 UTC, Techno-Disaster commented
> i could try checking it in windows and will see why the tests failed

did you test it on windows?

2021-11-28 16:34 UTC, AshishSingh2001 commented
The drag and drop is working fine in windows
I found some parts of the drag and drop different from the normal file select will make a updated PR soon

2023-02-08 00:08 UTC, Techno-Disaster commented
#41

2023-02-08 00:08 UTC, closed without merging