Output Settings Browse widget size fixed
CCExtractor/ccextractorfluttergui pull request #23
Opened 2021-12-30 08:37 UTC by ItsAdityaKSingh

## This PR solves issues:
- #21 
- #22 

Screenshot:
<img width="792" alt="Screenshot 2021-12-30 at 2 02 38 PM" src="https://user-images.githubusercontent.com/69353350/147735203-42806250-0cd3-44e8-88c0-e0d84d179e52.png">

### Along with this, the PR includes-
- Sizer package added for sizing-related references.
- macOS system generated files for successful execution in macOS environment.

2021-12-30 08:38 UTC, ItsAdityaKSingh commented
@Techno-Disaster Could you review this?

2021-12-30 11:42 UTC, Techno-Disaster commented
Check https://github.com/CCExtractor/ccextractorfluttergui/issues/22#issuecomment-1002991817

2021-12-30 11:42 UTC, Techno-Disaster requested changes

2021-12-30 11:42 UTC, Techno-Disaster commented on pubspec.yaml
> +  sizer: ^2.0.15
why?

2021-12-30 12:46 UTC, ItsAdityaKSingh commented on pubspec.yaml
> +  sizer: ^2.0.15
Wanted to use it for future sizing-related issues; it's a useful package to use instead of writing long MediaQuery lines or adjusting constant sizes!

2021-12-30 12:47 UTC, ItsAdityaKSingh commented
> Check [#22 (comment)](https://github.com/CCExtractor/ccextractorfluttergui/issues/22#issuecomment-1002991817)

Sure. I would remove the banner back to `true`.

2021-12-30 13:12 UTC, ItsAdityaKSingh commented
@Techno-Disaster The required changes are done. You may merge this PR!

2021-12-30 18:29 UTC, Techno-Disaster commented on pubspec.yaml
> +  sizer: ^2.0.15
Don't see it used anywhere, can you remove it for now?

2021-12-30 18:30 UTC, Techno-Disaster commented
Looks like ci is failing

2021-12-30 18:35 UTC, ItsAdityaKSingh commented
> Looks like ci is failing

I ran the format test on my local machine and seems like there's no issue locally. Any idea why it is failing here? @Techno-Disaster

2021-12-31 07:33 UTC, ItsAdityaKSingh commented
@Techno-Disaster I have updated the PR, and the CI tests pass now. You may merge this!

2022-01-01 15:22 UTC, Techno-Disaster commented
updating packages can be done in a different version

2022-01-01 15:22 UTC, Techno-Disaster commented on lib/screens/settings/components/current_command.dart
> -                    padding: const EdgeInsets.only(top: 10, left: 10),
why?

2022-01-01 15:27 UTC, ItsAdityaKSingh commented on lib/screens/settings/components/current_command.dart
> -                    padding: const EdgeInsets.only(top: 10, left: 10),
Due to covering up of command!

Screenshot -
<img width="782" alt="Screenshot 2022-01-01 at 6 42 12 PM" src="https://user-images.githubusercontent.com/69353350/147853975-4636844a-cb53-40ba-b300-76b8b6328c55.png">

So removing padding makes space and no issue of rendering occurs as well.

2022-01-11 21:41 UTC, Techno-Disaster commented on macos/Podfile
> +platform :osx, '10.11'
Can you remove these auto generated files? We can add this in some other PR.

2022-01-12 06:47 UTC, ItsAdityaKSingh commented on macos/Podfile
> +platform :osx, '10.11'
Sure!

2022-01-22 12:35 UTC, merged