render overflow issue
CCExtractor/ccextractorfluttergui pull request #8
Opened 2021-11-14 13:32 UTC by M-A-D-A-R-A

#7 

![image](https://user-images.githubusercontent.com/56160262/141683307-a86cd718-8ff8-4928-b7b7-4d17a06f7450.png)

2021-11-14 13:55 UTC, Techno-Disaster requested changes

2021-11-14 13:55 UTC, Techno-Disaster commented on lib/screens/settings/components/current_command.dart
> +                      // maxLines: 2,
Quick question why remove this? Also how does the command container look when you have a super big command? (lots of params passed?, a screenshot would be helpful here)

2021-11-14 17:47 UTC, M-A-D-A-R-A commented on lib/screens/settings/components/current_command.dart
> +                      // maxLines: 2,
That `max Lines` one i forget to undo lol , i was just cheaking it out hows its affecting the text and since the whole container is in SingleChildScrollView i guess that wont be a issue. I added one line in that text to check it out.
![image](https://user-images.githubusercontent.com/56160262/141692045-8d018466-cf2a-400c-8ed6-c02752d4c9f9.png)

 if u want i can change the size of container.

2021-11-15 05:08 UTC, Techno-Disaster commented on lib/screens/settings/components/current_command.dart
> +                      // maxLines: 2,
try with 3 line long text maybe? I'm pretty sure I added that there for some reason.

2021-11-15 11:03 UTC, M-A-D-A-R-A commented on lib/screens/settings/components/current_command.dart
> +                      // maxLines: 2,
Yeah , so if the text is more than 2 lines, the input scrolls vertically. so what should I do now ?

2021-11-16 07:47 UTC, M-A-D-A-R-A commented on lib/screens/settings/components/current_command.dart
> +                      // maxLines: 2,
Should i uncomment that `maxLines` ?

2021-11-17 05:10 UTC, M-A-D-A-R-A commented on lib/screens/settings/components/current_command.dart
> +                      // maxLines: 2,
Any further reviews from Your side so i could work on that?

2021-11-17 11:40 UTC, Techno-Disaster commented on lib/screens/settings/components/current_command.dart
> +                      // maxLines: 2,
![image](https://user-images.githubusercontent.com/52817235/142193936-3ebe2c12-7cf1-45f0-b14c-60aa199baf9c.png)

why was this padding removed?

2021-11-17 11:40 UTC, Techno-Disaster commented
![image](https://user-images.githubusercontent.com/52817235/142194083-e4740a58-64d1-4432-800d-2391c10784dc.png)

why was this padding removed?

2021-11-19 16:02 UTC, M-A-D-A-R-A commented
> ![image](https://user-images.githubusercontent.com/52817235/142194083-e4740a58-64d1-4432-800d-2391c10784dc.png)
> 
> why was this padding removed?

I 

> ![image](https://user-images.githubusercontent.com/52817235/142194083-e4740a58-64d1-4432-800d-2391c10784dc.png)
> 
> why was this padding removed?

I didnt removed it , i just adjusted it according the new container height.

2021-11-22 19:45 UTC, Techno-Disaster commented
Tests failed, can you look into it?

2021-12-12 14:06 UTC, M-A-D-A-R-A commented
how to remove this build fail for linux? Im working on windows.

2021-12-14 22:19 UTC, merged